Server:
  Mode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 1000
  LogPath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  Type: mysql
  Username: root
  Password: qweasdzxc123!@#
  Host:
  Project: blob
  MaxIdleConns: 10
  MaxOpenConns: 30
  